version: "1.0"
services:
  vprodb:
    build:
      context: ./Docker-files/db
    image: chyegembaj/vprofiledb
    container_name: vprodb
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSSWORD=admin123
  
  vprocache01:
    image: memcached
    ports:
      - "11211:11211"
  vpromq01:
    image: rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  vproapp:
    build:
      context: ./Docker-files/app
    image: chyegembaj/vprofileapp
    container_name: vprofileapp
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps
  
  vproweb:
    build:
      context: ./Docker-files/web
    image: chyegembaj/vprofileweb
    container_name: vprofileweb
    ports:
      - "80:80"

  volumes:
    vproappdata: {}
    vprodbdata: {}
  
    
