version: '3.8'
services:
  vprodb:
    image: wajidse102/vprofiledb
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass

  vprocache01:
    image: memcached
    ports:
      - "11211:11211"

  vpromq01:
    image: rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  vproapp:
    image: wajidse102/vprofileapp
    ports:
      - "8080:8080"
    volumes: 
      - vproappdata:/usr/local/tomcat/webapps

  vproweb:
    image: wajidse102/vprofileweb
    ports:
      - "80:80"
volumes:
  vprodbdata: {}
  vproappdata: {}