version: '3.8'
services:
  vprodb:
    build:
      context: ./Docker-files/db
    image: junaid121/vprofiledb
    container_name: vprodb  
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD=vprodbpass
  vprocache01:
    image: memcached
    ports:
      - "11211:11211"
  vpromq01:
    image: rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAUKT_PASS=guest    

  vproapp:
    build:
      context: ./Docker-files/app
    image: junaid121/vprofileapp
    container_name: vproapp  
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps

  vproweb:
    build:
      context: ./Docker-files/web
    image: junaid121/vprofileweb
    container_name: vproweb  
    ports:
      - "80:80"
volumes:
  vprodbdata: {}    
  vproappdata: {}  