apiVersion: v1
kind: Service
metadata:
  name: vproapp-service
spec:
  ports:
  - port: 30001
    nodePort: 30001
    targetPort: vproapp-port
    protocol: TCP
  selector:
    app: vproapp
  type: NodePort
